syntax = "proto3";

package ServiceData;

service ServiceData{
    rpc serviceStatus (EmptyRequest) returns (StatusServer);
    rpc usuariolist (EmptyRequest) returns (UsuariosList);
    rpc usuarioByEmail (UsuarioByEmailRequest) returns (Usuario);

    rpc usuarioListStream (EmptyRequest) returns (stream Usuario);
}

message EmptyRequest {}

message UsuarioByEmailRequest {
    string email = 1;
}

message StatusServer {
    bool act = 1;
    string message = 2;
}

message Usuario {
    string nombre = 1;
    string apellido = 2;
    string direccion = 3;
    string email = 4;
}

message UsuariosList {
    repeated Usuario usuarios = 1;
}
